USE sample2
GO


CREATE TABLE EMP(
EmployeeID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(30) NOT NULL,
ManagerID INT)


INSERT INTO EMP
VALUES
('HAMZA',2),('ROB',3),('SARA',1),('DAN', NULL),('YASMINE',4)