USE sample2
GO



CREATE TABLE tblGender (
GenderID  INT NOT NULL PRIMARY KEY,
GENDER  NVARCHAR(50) NOT NULL
)

GO


CREATE TABLE tblEmployee (

EmployeeID INT NOT NULL PRIMARY KEY,
NAME NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL,
GenderID INT NOT NULL,
FOREIGN KEY (GenderID) REFERENCES tblGender (GenderID))

Go
